services:
  firefly-pluxee-bridge:
    build: https://github.com/semiBE/pluxee-firefly-bridge.git#main
    container_name: firefly-pluxee-bridge
    restart: no
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks: 
      - firefly_iii
    environment:
      MAT_EMAIL: ${MAT_EMAIL}
      GIU_EMAIL: ${GIU_EMAIL}
      MAT_PWD: ${MAT_PWD}
      GIU_PWD: ${GIU_PWD}
      URL: ${URL}
      API_TOKEN: ${API_TOKEN}

networks:
  firefly_iii:
     driver: bridge
     external: true
